Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> #OpenCV'de cv.blur fonksiyonu, bir görüntüye belirli bir kernel (çekirdek) boyutunda bir ortalamalı bulanıklık uygulamak için kullanılır.
>>> #cv.GaussianBlur fonksiyonu, bir görüntüye Gaus bulanıklığı uygulamak için kullanılır.
>>> #cv2.bilateralFilter fonksiyonu, bir görüntü üzerinde bilateral filtreleme uygulamak için kullanılır. Bilateral filtreleme, kenarları korurken görüntüyü yumuşatma amacı taşır ve gürültü azaltma özelliği bulunur.
>>> #cv2.medianBlur fonksiyonu, bir görüntü üzerinde median (ortanca) filtreleme uygulamak için kullanılır.
>>> #
>>> import cv2 as cv
... 
... img = cv.imread('Photos/cats.jpg')
... 
... cv.imshow('Cats', img)
... average=cv.blur(img,(3,3))
... cv.imshow(‘Average Blur’,average)
... 
... cv.waitKey(o)
... 
... 
... 
... 
... 
... 
... import cv2 as cv
... 
... img = cv.imread('Photos/cats.jpg')
... 
... cv.imshow('Cats', img)
... average=cv.blur(img,(3,3))
... cv.imshow(‘Average Blur’,average)
... gauss=cv.GaussianBlur(img,(3,3),0)
... cv.imshow(‘Gaussian Blur’,gauss)
... median=cv.medianBlur(img,3)
... cv.imshow(‘Median Blur’,median)
... 
... bilateral=cv.bilatearlFilter(img,5,15,15)
... 
