Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
#Bu kod satırı, bir renkli görüntüyü (BGR formatında) üç renk kanalına ayırmak için kullanılır. cv.split fonksiyonu, bir görüntünün renk kanallarını ayırmak için kullanılır ve bu renk kanallarını ayrı ayrı değişkenlere atar.
#b: Mavi (Blue) kanal
#g: Yeşil (Green) kanal
#r: Kırmızı (Red) kanal
#cv.imshow('Blue', b) kodunu kullanıyorsanız, bu kod mavi kanalı temsil eden b değişkenini görselleştirmek için kullanılır.
#print(b.shape)  bu kod mavi kanalın şeklini (boyutlarını) ekrana yazdırmak için kullanılır
>>> import cv2 as cv
... 
... 
... import numpy as np
... 
... img = cv.imread('Photos/boston.jpg')
... 
... 
... cv.imshow('Boston', img)
... 
... 
... b,g,r = cv.split(img)
... 
... 
... 
... cv.imshow('Blue', b)
... 
... 
... cv.imshow('Green', g)
... 
... 
... 
... cv.imshow('Red', r)
... 
... 
... 
... print(img.shape)
... 
... 
... 
... print(b.shape)
... 
... 
... print(g.shape)
... 
... 
... print(r.shape)
... 
... 
