Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
#plt.imshow(img) ifadesi, matplotlib kütüphanesini kullanarak bir görüntüyü görselleştirmek amacıyla yaygın olarak kullanılır.
#Bu kod satırı, bir görüntü dosyasını okumak için OpenCV kütüphanesini kullanır. cv.imread fonksiyonu, belirtilen dosya yolundaki bir görüntüyü okuyarak bir NumPy dizisi olarak döndürür.
>>> #
... #Bu kod satırı, OpenCV kütüphanesini kullanarak bir Python programında görüntü işleme işlemleri yapabilmek için cv2 adını kullanmayı sağlar. cv2 genellikle OpenCV kütüphanesinin kısaltmasıdır ve bu adla kütüphanenin fonksiyonlarına ve modüllerine erişilebilir.
>>> 
... import cv2 as cv
... 
... img = cv.imread('Photos/boston.jpg')
... 
... cv.imshow('Boston', img)
... 
... #BGR to Grayscale
... gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY) 
... cv.imshow('Gray', gray
... 
... 
... cv.waitKey(0)
... 
... 
... 
... 
... 
... import cv2 as cv
... 
... 
... 
... import matplotlib.pyplot as plt
... 
... img = cv.imread('Photos/boston.jpg')
... 
... 
... 
... cv.imshow('Boston', img)
... 
... 
... plt.imshow(img)
... 
