Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
#"lap" görüntü işleme ve işaret işleme alanlarında "Laplacian" operatörünü ifade etmek için kullanılır. Laplacian operatörü, bir görüntüdeki yoğunluk değişimlerini tespit etmek veya kenarları vurgulamak için kullanılır.
#"Sobelx" ifadesi, görüntü işleme alanında sıkça kullanılan bir terimdir ve Sobel operatörünün x-eksenine uygulandığını ifade eder
import cv2 as cv



import numpy as np


img = cv.imread('Photos/cats.jpg')

... 
... 
... cv.imshow('Cats', img)
... 
... 
... gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
... 
... 
... 
... cv.imshow('Gray', gray)
... 
... 
... 
... 
... lap = cv. Laplacian (gray, cv.CV_64F)
... 
... 
... 
... lap = np.uint8(np.absolute (lap))
... 
... 
... 
... cv.imshow('Laplacian', lap)
... 
... 
... 
... 
... 
... 
... sobelx = cv. Sobel (gray, cv.CV_64F, 1, 0)
... 
... 
... 
... sobely = cv.Sobel (gray, cv.CV_64F, 0,1)
... 
... 
... cv.imshow(‘Sobel X’,sobelx)
... cv.imshow(‘Sobel Y’,sobely)
... 
