Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
#Haar Cascade, nesne tanıma için kullanılan bir özellik tabanlı nesne tanıma yöntemidir. Bu yöntem, özellikle yüz tanıma için popülerdir, ancak diğer nesne türleri için de kullanılabilir. Haar Cascade, öğrenilmiş özelliklere dayanarak nesneleri tanıyan bir sınıflandırıcıdır.
# "faces_rect"  bir yüz tanıma uygulamasında tespit edilen yüzlerin koordinatlarını içeren bir değişkeni ifade eder.
#cv.rectangle fonksiyonu, OpenCV kütüphanesinde dikdörtgen çizmek için kullanılır.
>>> import cv2 as cv
... 
... 
... 
... img = cv.imread('Photos/lady.jpg')
... 
... 
... 
... cv.imshow('Person', img)
... 
... 
... 
... gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
... 
... 
... cv.imshow('Gray Person', gray)
... 
... 
... 
... haar_cascade = cv. CascadeClassifier(‘haar_face.xml')
... 
... 
... faces_rect = haar_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=3)
... 
... 
... print(f'Number of faces found = (len(faces_rect)}')
... 
... 
... 
... for (x,y,w,h) in faces_rect:
... 
... 
... 
... cv.rectangle(img, (x,y), (x+w,y+h), (0,255,0), thickness=2)
... 
... cv.imshow(‘Detected Faces’,img)
... cv.waitKey(0)
