Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> #Mask, bir görüntü üzerinde belirli bir bölgeyi seçmek veya vurgulamak amacıyla kullanılan bir siyah-beyaz görüntüdür.
>>> #img.shape ifadesi, bir görüntünün boyutlarını (genişlik, yükseklik ve kanal sayısı) içeren bir tuple'ı döndürür. Görüntü bir NumPy dizisi olduğu için, bu özellik, bu dizinin boyutlarını gösterir.
>>> #
>>> import cv2 as cv
... 
... 
... 
... import numpy as np
... 
... img = cv.imread('Photos/cats.jpg')
... 
... 
... 
... cv.imshow('Cats', img)
... 
... 
... 
... blank = np.zeros(img.shape[:2], dtype='uint8')
... 
... 
... 
... cv.imshow('Blank Image', blank)
... 
... 
... 
... mask = cv.circle(blank, (img.shape[1]//2,img.shape[0]//2 ),100,255,-1)
... cv.imshow(‘Mask’,mask)
... 
... 
... 
... 
